name: Release Package

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest
            - name: Install dependencies
              run: bun install
            - name: Build
              run: bun run build
            - name: Authenticate with npm
              run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
            - name: Publish
              run: bun publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
